Revert - Split Nightly test (#153)

diff --git a/.github/workflows/reusable-CI-workflow.yml b/.github/workflows/reusable-CI-workflow.yml
--- a/.github/workflows/reusable-CI-workflow.yml
+++ b/.github/workflows/reusable-CI-workflow.yml
@@ -3,12 +3,12 @@ name: 'CI reusable workflow'
 on:
   workflow_call:
 
+permissions:
+  contents: read
+
 env:
   COMPOSER_PREFER_STABLE: '1'
   TEST_OUTPUT_STYLE: pretty
-
-permissions:
-  contents: read
 
 jobs:
   fetch-supported-versions:
@@ -162,3 +162,47 @@ jobs:
       - name: Dependencies check
         if: ${{ github.event_name == 'pull_request' }}
         uses: actions/dependency-review-action@v4
+
+  nightly-tests:
+    name: Nightly
+    needs: [ fetch-supported-versions, tests ]
+    if: ${{ github.event_name == 'push' || ( github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'with-nightly-tests') ) }}
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    continue-on-error: true
+    env:
+      PHP_VERSION: ${{ needs.fetch-supported-versions.outputs.php-next }}
+      COMPOSER_IGNORE_PLATFORM_REQ: 'php+'
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v5
+
+      - name: Setup PHP ${{ env.PHP_VERSION }}
+        id: setup-php
+        uses: shivammathur/setup-php@v2
+        env:
+          update: true # whether to use latest available patch for the version or not
+          fail-fast: true # step will fail if an extension or tool fails to set up
+        with:
+          php-version: ${{ env.PHP_VERSION }}
+          tools: composer
+          coverage: none
+
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+
+      - name: Setup cache for PHP ${{ steps.setup-php.outputs.php-version }}
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ steps.composer-cache.outputs.dir }}
+          # Clear the cache if composer.json (as composer.lock is not available) has been updated
+          key: tests-php${{ steps.setup-php.outputs.php-version }}-${{ hashFiles('composer.json') }}
+
+      - name: Build with PHP ${{ steps.setup-php.outputs.php-version }}
+        run: make build
+
+      - name: Test
+        run: make test-unit && make test-functional
